Repository w3c/webtransport, pull requests merged in 2022-03, with the labels that each got.

#380 Simplify cleanup steps by avoiding type variance.
  index.bs
Labels: Editorial, Editors can integrate

#391 Improve markup for definitions and automatic links
  .github/workflows/pr-push.yml
  index.bs
Labels: Editorial

#385 Add wt.reliability attr and {requireUnreliable} constructor option.
  index.bs
Labels: Editors can integrate
