Repository w3c/webtransport, pull requests merged in 2023-02, with the labels that each got.

#460 Align WebTransportError with guidance.
  index.bs
Labels: Needs test

#462 Rely on allowPooling's default value.
  index.bs
Labels: Editorial

#467 Update protocol mapping table
  index.bs
Labels: Editorial

#421 Add rate control event
  index.bs
Labels: Editors can integrate

#473 Linkify "fire an event" concept to clarify steps and interface
  index.bs
Labels: Editorial
